"use client";
import "@/app/_styles/globals.css";
import Header from "./_components/Header";
import { ReduxProvider } from "./_lib/redux-provider";
import { SessionProvider } from "next-auth/react";

import "photoswipe/dist/photoswipe.css";

// google font 字體設定
import { Josefin_Sans } from "next/font/google";
import NextProviders from "./_components/NextProviders";
const josefin = Josefin_Sans({
  subsets: ["latin"],
  display: "swap",
});

// Only work in Server Component
// export const metadata = {
//   title: "Luxury Cosy Nest.",
//   description: "Generated by Next.js",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Luxury Cosy Nest</title>
        <meta name="Generated by Next.js" content="Generated by Next.js" />
      </head>
      <body className={`${josefin.className}`}>
        <NextProviders>
          <ReduxProvider>
            <SessionProvider>
              <Header />
              {children}
            </SessionProvider>
          </ReduxProvider>
        </NextProviders>
      </body>
    </html>
  );
}
